name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        uses: npm install

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.ftpx.forpsi.com }}
          username: ${{ secrets.www.topstropuklid.cz }} 
          password: ${{ secrets.rWmD73Adcx }}
          local-dir: build/
          server-dir: /path/to/your/server/directory